type = "directrequest"
schemaVersion = 1
name = "dclimate-apiv4-mumbai"
externalJobID = "b886eeae-31f7-46ac-898c-5b568a9a5503"
maxTaskDuration = "30s"
contractAddress = "0x59FA4e3Fd486E5798C8F8d884f0F65A51A5dFF43"
evmChainID = "80001"
minContractPaymentLinkJuels = "0"
observationSource = """
    decode_log   [type=ethabidecodelog
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]
    decode_cbor  [type=cborparse data="$(decode_log.data)"]
    api_adapter  [type="bridge" name="api-adapter" timeout="600s" requestData="{\\"data\\":{\\"request_url\\": $(decode_cbor.request_url), \\"spatial_parameters\\": $(decode_cbor.spatial_parameters), \\"temporal_parameters\\": $(decode_cbor.temporal_parameters)}}"]
    
    decode_log -> decode_cbor -> api_adapter

    unit_parse   [type=jsonparse path="result,unit" data="$(api_adapter)"]
    data_parse   [type=jsonparse path="result,data" data="$(api_adapter)"]

    encode_data  [type=ethabiencode abi="(bytes32 requestId, uint64 _value, string _unit)" data="{ \\"requestId\\": $(decode_log.requestId), \\"_value\\": $(data_parse), \\"_unit\\": $(unit_parse) }"]
    encode_tx    [type=ethabiencode
                  abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"
                 ]
    submit_tx    [type=ethtx from="[\\"0x7bF0F792609E25Dd3048D489BDABe5017195481e\\"]" evmChainID="80001" to="0x59FA4e3Fd486E5798C8F8d884f0F65A51A5dFF43" data="$(encode_tx)"]
    
    api_adapter -> unit_parse -> encode_data
    api_adapter -> data_parse -> encode_data
    encode_data -> encode_tx -> submit_tx
"""