name: arbol-dapp-local
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.9
  - geopandas
  - werkzeug==2.2.2
  - typing-extensions<4.6.0
  - numcodecs
  - gunicorn[gevent]
  - gevent
  - rioxarray
  - xarray
  - psutil
  - pip:
    - -e ./repos/dweather
    - -e ./repos/ipldstore
    - -e ./repos/zarrclient
    - flask==2.1.0
    - cloudpickle
    - multiaddr
    - coincurve
    - pycryptodome
    - pynacl
    - pymongo
    - python-dotenv