name: arbol-dapp
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.9
  - geopandas
  - werkzeug==2.2.2
  - typing-extensions<4.6.0
  - numcodecs
  - gunicorn[gevent]
  - gevent
  - rioxarray
  - xarray
  - psutil
  - pip:
    - git+https://git@github.com/dmp267/dWeather-Python-Client.git
    - git+https://git@github.com/dmp267/ipldstore.git
    - git+https://github.com/Arbol-Project/zarr-client
    - flask==2.1.0
    - cloudpickle
    - multiaddr
    - coincurve
    - pycryptodome
    - pynacl
    - pymongo
    - python-dotenv





