name: Adapter Deployment
on:
  push:
    branches:
      - main

# permissions:
#   id-token: write
#   contents: read

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v4

    - name: Checkout Dependency repository
      uses: actions/checkout@v4
      with:
        repository: Arbol-Project/zarr-client
        token: ${{ secrets.DOCKER_PAT }}
        path: zarr-client
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        # role-to-assume: arn:aws:iam::574269834288:role/adapter-github-actions-role
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Get ECS Integration
      run: curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build
      env: 
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: external-adapter
        IMAGE_TAG: ${{ github.sha }}
      # docker buildx build --platform=linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

    - name: Push External Adapter to Amazon ECR
      id: push-adapter-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: external-adapter
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:latest"

    - name: Download Task Definitions
      run: |
        aws ecs describe-task-definition --task-definition dapp-task-adapters --query taskDefinition > task-definition-adapters.json
      
    - name: Modify Amazon ECS task definition with External Adapter container
      id: render-adapter-container
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition-adapters.json
        container-name: external-adapter
        image: ${{ steps.push-adapter-image.outputs.image }}
      
    - name: Deploy External Adapters to Amazon ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-adapter-container.outputs.task-definition }}
        service: dapp-service-adapters
        cluster: dapp-cluster