name: Adapter Deployment
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::574269834288:role/adapter-github-actions-role
        aws-region: us-east-1
    
    - name: Setup ssh-agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Get ECS Integration
      run: curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v5
      with:
        context: adapter
        push: false
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/external-adapter:${{ github.sha }}
          ${{ steps.login-ecr.outputs.registry }}/external-adapter:latest
        ssh: |
          default="${{ env.SSH_AUTH_SOCK }}"

    - name: Push External Adapter to Amazon ECR
      id: push-adapter-image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
        REPOSITORY: external-adapter
      run: |
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$REGISTRY/$REPOSITORY:$IMAGE_TAG"
        docker push $REGISTRY/$REPOSITORY:latest
        echo "::set-output name=image::$REGISTRY/$REPOSITORY:latest"

    - name: Download Task Definitions
      run: |
        aws ecs describe-task-definition --task-definition dapp-task-adapters --query taskDefinition > task-definition-adapters.json
      
    - name: Modify Amazon ECS task definition with External Adapter container
      id: render-adapter-container
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition-adapters.json
        container-name: external-adapter
        image: ${{ steps.push-adapter-image.outputs.image }}
      
    - name: Deploy External Adapters to Amazon ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-adapter-container.outputs.task-definition }}
        service: dapp-service-adapters
        cluster: dapp-cluster